<<<<<<< HEAD
# Generated by Django 4.2 on 2023-07-25 01:34
=======
# Generated by Django 4.2 on 2023-07-25 00:46
>>>>>>> 89d32f8dd5b31fb49e5d503b6a039dab3c642f86

import cwmapp.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'msg': 'A user with that username already exists.'}, help_text='この名前は公開されます。', max_length=50, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('email', models.EmailField(blank=True, max_length=254, primary_key=True, serialize=False, verbose_name='email address')),
<<<<<<< HEAD
                ('userid', models.CharField(default=uuid.UUID('e709ea52-c4fd-4dc0-9cfa-8bd20456037b'), error_messages={'msg': 'fuck!'}, help_text='この名前は公開されません。', max_length=100, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='userid')),
=======
                ('userid', models.CharField(default=uuid.UUID('0ec96737-cd69-4943-a3db-4f3b87546a57'), error_messages={'msg': 'fuck!'}, help_text='この名前は公開されません。', max_length=100, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='userid')),
>>>>>>> 89d32f8dd5b31fb49e5d503b6a039dab3c642f86
                ('image', models.ImageField(upload_to='images/')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', cwmapp.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment_user_mail', models.EmailField(max_length=254)),
                ('comment_music_id', models.TextField()),
                ('comment_good', models.IntegerField()),
                ('comment_text', models.TextField()),
                ('comment_posted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_user_mail', models.EmailField(max_length=254)),
                ('good_music_id', models.TextField()),
<<<<<<< HEAD
                ('good_bool', models.BooleanField(default=False)),
=======
                ('good_num', models.BooleanField(default=False)),
                ('sum_good', models.IntegerField()),
>>>>>>> 89d32f8dd5b31fb49e5d503b6a039dab3c642f86
            ],
        ),
        migrations.CreateModel(
            name='HistoryList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_user_mail', models.EmailField(max_length=254)),
                ('history_music_id', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LikeList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_user_mail', models.EmailField(max_length=254)),
                ('like_music_id', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('music_id', models.TextField(primary_key=True, serialize=False)),
                ('music_star', models.IntegerField()),
                ('music_ad', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('reply_id', models.AutoField(primary_key=True, serialize=False)),
                ('reply_comment_id', models.IntegerField()),
                ('reply_user_mail', models.EmailField(max_length=254)),
                ('reply_text', models.TextField()),
                ('reply_posted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star_user_mail', models.EmailField(max_length=254)),
                ('star_music_id', models.TextField()),
                ('star_num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UploadImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_name', models.CharField(max_length=50)),
                ('user_mail', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('user_pass', models.CharField(max_length=30)),
                ('user_image', models.ImageField(upload_to='images/')),
                ('user_birthday', models.DateField()),
            ],
        ),
        migrations.AddConstraint(
            model_name='star',
            constraint=models.UniqueConstraint(fields=('star_user_mail', 'star_music_id'), name='unique_star'),
        ),
        migrations.AddConstraint(
            model_name='good',
            constraint=models.UniqueConstraint(fields=('good_user_mail', 'good_music_id'), name='unique_good'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
