# Generated by Django 4.2 on 2023-05-22 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment_text', models.TextField()),
                ('comment_user_mail', models.EmailField(max_length=254)),
                ('comment_music_id', models.IntegerField()),
                ('comment_good', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HistoryList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_music_id', models.IntegerField()),
                ('history_user_mail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='LikeList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_music_id', models.IntegerField()),
                ('like_user_mail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('music_id', models.AutoField(primary_key=True, serialize=False)),
                ('music_name', models.TextField()),
                ('music_star', models.IntegerField(default=0)),
                ('music_image', models.CharField(max_length=200)),
                ('music_artistname', models.TextField()),
                ('music_albumname', models.TextField()),
                ('music_preview', models.TextField()),
                ('music_playurl', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_comment_id', models.IntegerField()),
                ('result_text', models.TextField()),
                ('result_user_mail', models.EmailField(max_length=254)),
                ('result_music_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_name', models.CharField(max_length=50)),
                ('user_mail', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('user_pass', models.CharField(max_length=50)),
                ('user_image', models.CharField(max_length=200)),
                ('user_birthday', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
