# Generated by Django 4.2 on 2023-05-26 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_name', models.CharField(max_length=50)),
                ('user_mail', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('user_pass', models.CharField(max_length=30)),
                ('user_image', models.ImageField(upload_to='images/')),
                ('user_birthday', models.DateTimeField()),
            ],
        ),
    ]
