# Generated by Django 4.2 on 2023-06-16 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cwmapp', '0002_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historylist',
            name='history_music_id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='likelist',
            name='like_music_id',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
