# Generated by Django 4.2 on 2023-06-16 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cwmapp', '0003_alter_historylist_history_music_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
