# Generated by Django 4.2 on 2023-09-13 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cwmapp', '0004_alter_customuser_userid'),
        ('cwmapp', '0004_uploadimage'),
    ]

    operations = [
    ]
