# Generated by Django 4.2 on 2023-07-19 05:57

import django.contrib.auth.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cwmapp', '0005_good_alter_customuser_userid_good_unique_good'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='sum_good',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='userid',
            field=models.CharField(default=uuid.UUID('95f773d2-8d9c-4756-8140-7f2ed7f0989b'), error_messages={'msg': 'fuck!'}, help_text='この名前は公開されません。', max_length=100, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='userid'),
        ),
    ]
