# Generated by Django 4.2 on 2023-07-19 06:05

import django.contrib.auth.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cwmapp', '0006_good_sum_good_alter_customuser_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='userid',
            field=models.CharField(default=uuid.UUID('76f0b103-0b7e-4d83-839d-33fcd4f23635'), error_messages={'msg': 'fuck!'}, help_text='この名前は公開されません。', max_length=100, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='userid'),
        ),
        migrations.AlterField(
            model_name='good',
            name='sum_good',
            field=models.IntegerField(),
        ),
    ]
