# Generated by Django 4.2 on 2023-07-20 07:19

import django.contrib.auth.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cwmapp', '0008_alter_customuser_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='good',
            old_name='good_num',
            new_name='good_bool',
        ),
        migrations.RemoveField(
            model_name='good',
            name='sum_good',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='userid',
            field=models.CharField(default=uuid.UUID('730a3a42-2c93-49d3-8ad5-4d58f8001416'), error_messages={'msg': 'fuck!'}, help_text='この名前は公開されません。', max_length=100, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='userid'),
        ),
    ]
