# Generated by Django 4.2 on 2023-07-24 13:43

import django.contrib.auth.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cwmapp', '0011_alter_customuser_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentGood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_good_mail', models.EmailField(max_length=254)),
                ('comment_music_id', models.TextField()),
                ('comment_bool', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='userid',
            field=models.CharField(default=uuid.UUID('3e02cbb0-e9e8-4615-9c73-9d2ab6c284cc'), error_messages={'msg': 'fuck!'}, help_text='この名前は公開されません。', max_length=100, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='userid'),
        ),
        migrations.AddConstraint(
            model_name='commentgood',
            constraint=models.UniqueConstraint(fields=('comment_good_mail', 'comment_music_id'), name='unique_coment'),
        ),
    ]
