# Generated by Django 4.2 on 2023-07-24 14:38

import django.contrib.auth.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cwmapp', '0014_alter_customuser_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='userid',
            field=models.CharField(default=uuid.UUID('6b6be376-99cb-4b4a-b7b4-966d2e8a6b72'), error_messages={'msg': 'fuck!'}, help_text='この名前は公開されません。', max_length=100, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='userid'),
        ),
    ]
