# Generated by Django 4.2 on 2023-07-24 15:42

import django.contrib.auth.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cwmapp', '0015_alter_customuser_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentgood',
            name='comment_music_id',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='userid',
            field=models.CharField(default=uuid.UUID('ac652451-22ca-416c-93ce-9ce21a1c0099'), error_messages={'msg': 'fuck!'}, help_text='この名前は公開されません。', max_length=100, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='userid'),
        ),
    ]
